default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV['PG_DB_NAME']%>
  username: <%= ENV['PG_USERNAME']%>
  password: <%= ENV['PG_PASSWORD'] || '' %>
  host: <%= ENV['PG_HOSTNAME'] || 'localhost' %>
  port: <%= ENV['PG_PORT'] || 5432 %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
